################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  #
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker: 
    watch: true
    exposedByDefault: false
################################################################
# Traefik Logging
################################################################
log:
  level: INFO
################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
################################################################
# https certificates
################################################################
# certificatesResolvers:
#   le:
#     acme:
#       email: maadanisepehr@gmail.com
#       storage: /letsencrypt/acme.json
#       tlsChallenge: {}
      