name: CI

run-name: ${{ github.actor }} is running workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      POSTGRES_DATABASE_URL: "sqlite:///:memory:"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools fastapi[all] sqlalchemy pytest flake8 pylint requests

      - name: Lint with flake8
        run: |
          echo "Linting the code..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        run: |
          echo "Running tests with pytest..."
          pytest --disable-warnings -v
          